name: mi_ruta_morelia
description: "A Flutter app for public transport in Morelia"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  http: ^1.3.0
  socket_io_client: ^2.0.3
  web_socket_channel: ^2.4.0
  cupertino_icons: ^1.0.8
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
